### PR TITLE
Add work-around for TEMP_FAILURE_RETRY to support musl

### PR DESCRIPTION
**Pull request by shawrkbait**
Add support for Alpine linux

### CODE REVIEW

**Comment by DanySpin97** [comment]
Any update on this Pull Request?

**Comment by alexlarsson** [comment]
bot, test pull request

**Comment by alexlarsson** [comment]
It looks right to me.

**Comment by alexlarsson** [comment]
Similar patch was merged in libglnx

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
